//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1234
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public decimal ID { get; set; }
        public decimal TeacherID { get; set; }
        public decimal DisciplineID { get; set; }
        public decimal StudentID { get; set; }
    }
}
