//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1234
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Role
    {
        public string Login { get; set; }
        public decimal Role { get; set; }
    
        public virtual User User { get; set; }
    }
}
